version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:11.5
    environment:
      POSTGRES_DB: tasklinker
      # You should definitely change the password in production
      POSTGRES_PASSWORD: passwordBDD
    volumes:
      - database_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
